1. 导入必要的包

In [17]:
!pip install finta
from finta import TA

Requirement already satisfied: finta in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (1.3)
Requirement already satisfied: numpy in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (from finta) (1.26.4)
Requirement already satisfied: pandas in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (from finta) (2.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (from pandas->finta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (from pandas->finta) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (from pandas->finta) (2023.3)
Requirement already satisfied: six>=1.5 in /home/gxj/anaconda3/envs/mt5/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->finta) (1.16.0)

In [1]:
# 注意pandas的版本2.1.4和numpy=1.26.4
import xgboost as xgb
from xgboost import XGBClassifier
import pandas as pd
import numpy as np
#!pip install fastparquet

# 准备数据

In [35]:
eurusd = pd.read_parquet('/opt/data/eurusd.parquet')
eurusd.info()
eurusd.head()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8224923 entries, 2000-05-30 17:27:00 to 2024-08-30 16:59:00
Data columns (total 5 columns):
 #   Column  Dtype
---  ------  -----
 0   open    float64
 1   high    float64
 2   low     float64
 3   close   float64
 4   volume  int64
dtypes: float64(4), int64(1)
memory usage: 376.5 MB

                       open    high     low   close  volume
timestamp
2000-05-30 17:27:00  0.9302  0.9302  0.9302  0.9302       0
2000-05-30 17:35:00  0.9304  0.9305  0.9304  0.9305       0
2000-05-30 17:38:00  0.9304  0.9304  0.9303  0.9303       0
2000-05-30 17:43:00  0.9301  0.9301  0.9300  0.9300       0
2000-05-30 17:44:00  0.9298  0.9298  0.9297  0.9297       0

In [33]:
eurusd['volume']= eurusd['volume'].astype(float)
eurusd

                        open     high      low    close  volume
timestamp
2000-05-30 17:27:00  0.93020  0.93020  0.93020  0.93020     0.0
2000-05-30 17:35:00  0.93040  0.93050  0.93040  0.93050     0.0
2000-05-30 17:38:00  0.93040  0.93040  0.93030  0.93030     0.0
2000-05-30 17:43:00  0.93010  0.93010  0.93000  0.93000     0.0
2000-05-30 17:44:00  0.92980  0.92980  0.92970  0.92970     0.0
...                      ...      ...      ...      ...     ...
2024-08-30 16:55:00  1.10482  1.10483  1.10473  1.10474     0.0
2024-08-30 16:56:00  1.10476  1.10481  1.10473  1.10478     0.0
2024-08-30 16:57:00  1.10477  1.10481  1.10472  1.10475     0.0
2024-08-30 16:58:00  1.10476  1.10478  1.10465  1.10474     0.0
2024-08-30 16:59:00  1.10473  1.10474  1.10453  1.10456     0.0

[8224923 rows x 5 columns]

In [36]:
eurusd.to_csv('~/mt5/chan.py/DataAPI/eurusd.csv')

In [28]:
df = eurusd
df['SMA5'] = TA.SMA(df, 5)
df['SMA10'] = TA.SMA(df, 10)
df['SMA20'] = TA.SMA(df, 20)
df['SMA60'] = TA.SMA(df, 60)
df['SMA120'] = TA.SMA(df, 120)
df['SMA200'] = TA.SMA(df, 200)
df['RSI'] = TA.RSI(df)
bb = TA.BBANDS(df)
df['BB_UPPER'] = bb['BB_UPPER']
df['BB_MIDDLE'] = bb['BB_MIDDLE']
df['BB_LOWER'] = bb['BB_LOWER']
df

,open,high,low,close,volume,SMA5,SMA10,SMA20,SMA60,SMA120,SMA200,RSI,BB_UPPER,BB_MIDDLE,BB_LOWER
timestamp,,,,,,,,,,,,,,,
2000-05-30 17:27:00,0.93020,0.93020,0.93020,0.93020,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-30 17:35:00,0.93040,0.93050,0.93040,0.93050,0.0,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN
2000-05-30 17:38:00,0.93040,0.93040,0.93030,0.93030,0.0,NaN,NaN,NaN,NaN,NaN,NaN,58.208955,NaN,NaN,NaN
2000-05-30 17:43:00,0.93010,0.93010,0.93000,0.93000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,34.749829,NaN,NaN,NaN
2000-05-30 17:44:00,0.92980,0.92980,0.92970,0.92970,0.0,0.930140,NaN,NaN,NaN,NaN,NaN,24.232509,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-30 16:55:00,1.10482,1.10483,1.10473,1.10474,0.0,1.104828,1.104904,1.104964,1.105124,1.105093,1.105164,30.015115,1.105161,1.104964,1.104767
2024-08-30 16:56:00,1.10476,1.10481,1.10473,1.10478,0.0,1.104798,1.104879,1.104956,1.105118,1.105091,1.105163,34.662675,1.105170,1.104956,1.104743
2024-08-30 16:57:00,1.10477,1.10481,1.10472,1.10475,0.0,1.104780,1.104854,1.104947,1.105112,1.105089,1.105161,32.898110,1.105180,1.104947,1.104715
2024-08-30 16:58:00,1.10476,1.10478,1.10465,1.10474,0.0,1.104768,1.104828,1.104932,1.105102,1.105085,1.105159,32.307712,1.105178,1.104932,1.104687
2024-08-30 16:59:00,1.10473,1.10474,1.10453,1.10456,0.0,1.104714,1.104793,1.104908,1.105090,1.105080,1.105157,23.969251,1.105198,1.104908,1.104618

In [30]:
# fill nan
df.fillna(0, inplace=True)
df.head(30)

,open,high,low,close,volume,SMA5,SMA10,SMA20,SMA60,SMA120,SMA200,RSI,BB_UPPER,BB_MIDDLE,BB_LOWER
timestamp,,,,,,,,,,,,,,,
2000-05-30 17:27:00,0.9302,0.9302,0.9302,0.9302,0.0,0.00000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
2000-05-30 17:35:00,0.9304,0.9305,0.9304,0.9305,0.0,0.00000,0.00000,0.000000,0.0,0.0,0.0,100.000000,0.000000,0.000000,0.000000
2000-05-30 17:38:00,0.9304,0.9304,0.9303,0.9303,0.0,0.00000,0.00000,0.000000,0.0,0.0,0.0,58.208955,0.000000,0.000000,0.000000
2000-05-30 17:43:00,0.9301,0.9301,0.9300,0.9300,0.0,0.00000,0.00000,0.000000,0.0,0.0,0.0,34.749829,0.000000,0.000000,0.000000
2000-05-30 17:44:00,0.9298,0.9298,0.9297,0.9297,0.0,0.93014,0.00000,0.000000,0.0,0.0,0.0,24.232509,0.000000,0.000000,0.000000
2000-05-30 18:29:00,0.9298,0.9299,0.9298,0.9299,0.0,0.93008,0.00000,0.000000,0.0,0.0,0.0,37.757395,0.000000,0.000000,0.000000
2000-05-30 18:37:00,0.9300,0.9300,0.9300,0.9300,0.0,0.92998,0.00000,0.000000,0.0,0.0,0.0,43.215423,0.000000,0.000000,0.000000
2000-05-30 18:40:00,0.9299,0.9299,0.9299,0.9299,0.0,0.92990,0.00000,0.000000,0.0,0.0,0.0,39.486516,0.000000,0.000000,0.000000
2000-05-30 18:41:00,0.9300,0.9300,0.9300,0.9300,0.0,0.92990,0.00000,0.000000,0.0,0.0,0.0,44.631567,0.000000,0.000000,0.000000
2000-05-30 18:42:00,0.9299,0.9299,0.9298,0.9299,0.0,0.92994,0.93004,0.000000,0.0,0.0,0.0,40.887744,0.000000,0.000000,0.000000
2000-05-30 18:43:00,0.9300,0.9300,0.9300,0.9300,0.0,0.92996,0.93002,0.000000,0.0,0.0,0.0,45.785254,0.000000,0.000000,0.000000
2000-05-30 18:45:00,0.9299,0.9299,0.9299,0.9299,0.0,0.92994,0.92996,0.000000,0.0,0.0,0.0,42.034739,0.000000,0.000000,0.000000
2000-05-30 18:46:00,0.9300,0.9300,0.9300,0.9300,0.0,0.92996,0.92993,0.000000,0.0,0.0,0.0,46.733706,0.000000,0.000000,0.000000
2000-05-30 18:50:00,0.9299,0.9299,0.9299,0.9299,0.0,0.92994,0.92992,0.000000,0.0,0.0,0.0,42.981388,0.000000,0.000000,0.000000
2000-05-30 18:51:00,0.9298,0.9298,0.9298,0.9298,0.0,0.92992,0.92993,0.000000,0.0,0.0,0.0,39.560666,0.000000,0.000000,0.000000
2000-05-30 18:52:00,0.9298,0.9300,0.9298,0.9299,0.0,0.92990,0.92993,0.000000,0.0,0.0,0.0,44.331876,0.000000,0.000000,0.000000
2000-05-30 18:55:00,0.9300,0.9300,0.9300,0.9300,0.0,0.92992,0.92993,0.000000,0.0,0.0,0.0,48.693665,0.000000,0.000000,0.000000
2000-05-30 18:56:00,0.9299,0.9299,0.9298,0.9298,0.0,0.92988,0.92992,0.000000,0.0,0.0,0.0,41.662628,0.000000,0.000000,0.000000
2000-05-30 18:57:00,0.9297,0.9297,0.9297,0.9297,0.0,0.92984,0.92989,0.000000,0.0,0.0,0.0,38.657036,0.000000,0.000000,0.000000
2000-05-30 18:59:00,0.9296,0.9296,0.9296,0.9296,0.0,0.92980,0.92986,0.929950,0.0,0.0,0.0,35.870256,0.930363,0.929950,0.929537
2000-05-30 19:00:00,0.9297,0.9297,0.9297,0.9297,0.0,0.92976,0.92983,0.929925,0.0,0.0,0.0,40.490304,0.930335,0.929925,0.929515
2000-05-30 19:04:00,0.9296,0.9296,0.9296,0.9296,0.0,0.92968,0.92980,0.929880,0.0,0.0,0.0,37.575082,0.930215,0.929880,0.929545
2000-05-30 19:05:00,0.9297,0.9297,0.9297,0.9297,0.0,0.92966,0.92977,0.929850,0.0,0.0,0.0,42.066995,0.930129,0.929850,0.929571
2000-05-30 19:11:00,0.9298,0.9298,0.9298,0.9298,0.0,0.92968,0.92976,0.929840,0.0,0.0,0.0,46.233481,0.930111,0.929840,0.929569
2000-05-30 19:12:00,0.9299,0.9300,0.9299,0.9300,0.0,0.92976,0.92978,0.929855,0.0,0.0,0.0,53.444973,0.930126,0.929855,0.929584
2000-05-30 19:13:00,0.9299,0.9299,0.9299,0.9299,0.0,0.92980,0.92978,0.929855,0.0,0.0,0.0,49.845075,0.930126,0.929855,0.929584
2000-05-30 19:17:00,0.9298,0.9299,0.9298,0.9299,0.0,0.92986,0.92977,0.929850,0.0,0.0,0.0,49.845075,0.930114,0.929850,0.929586
2000-05-30 19:18:00,0.9298,0.9299,0.9298,0.9299,0.0,0.92990,0.92978,0.929850,0.0,0.0,0.0,49.845075,0.930114,0.929850,0.929586
2000-05-30 19:21:00,0.9300,0.9301,0.9300,0.9301,0.0,0.92996,0.92982,0.929855,0.0,0.0,0.0,57.068504,0.930134,0.929855,0.929576
2000-05-30 19:22:00,0.9300,0.9300,0.9299,0.9299,0.0,0.92994,0.92985,0.929855,0.0,0.0,0.0,49.405642,0.930134,0.929855,0.929576

In [34]:
df.to_csv('~/mt5/chan.py/DataAPI/eurusd.csv')

## 添加指标

2.1 设置参数，进行训练

In [ ]:
# 单分类
params1 = {"seed":1412, "objective"::"binary:logistic","eval_metric":"logloss"} # 二分类交叉熵损失

# 多分类
params2 = {"seed":1412, "objective"::"multi:softmax","eval_metric":"mlogloss", "num_class": 10} # 二分类交叉熵损失

clf_binary = xgb.train(params1, data_binary, num_boost_round=100)

In [ ]:
from sklearn.metrics import accuracy_score as ACC # 当返回具体类别时，可以使用准确率
from sklearn.metrics import log_loss as logloss # 当返回概率时，则必须使用交叉熵损失

# 交叉验证

In [ ]:
result = xgb.cv(params2, data_multi, num_boost_round=100
    ,metrics = ("mlogloss", "merror") # 交叉验证的评估指标由cv中的参数metrics决定
    ,nfold = 5 # 补充交叉验证中所需的参数，nfold=5表示5折交叉验证
    ,seed=1412 #交叉验证的随机数种子，params中的是管理boosting过程的随机数种子
    )

In [ ]:
result

3. 初始化缠论

In [3]:
import json
from typing import Dict, TypedDict
from Chan import CChan
from ChanConfig import CChanConfig
from ChanModel.Features import CFeatures
from Common.CEnum import AUTYPE, DATA_SRC, KL_TYPE
from Common.CTime import CTime
from Plot.PlotDriver import CPlotDriver

4. 定义画图函数和参数

In [4]:
def plot(chan, plot_marker):
    plot_config = {
        "plot_kline": True,
        "plot_bi": True,
        "plot_seg": True,
        "plot_zs": True,
        "plot_bsp": True,
        "plot_marker": True,
    }
    plot_para = {
        "figure": {
            "x_range": 400,
        },
        "marker": {
            "markers": plot_marker
        }
    }
    plot_driver = CPlotDriver(
        chan,
        plot_config=plot_config,
        plot_para=plot_para,
    )
    plot_driver.save2img("label.png")

5. 定义特征字典

In [5]:
class T_SAMPLE_INFO(TypedDict):
    feature: CFeatures
    is_buy: bool
    open_time: CTime

6. 定义策略feature

In [6]:
def stragety_feature(last_klu):
    return {
        "open_klu_rate": (last_klu.close - last_klu.open)/last_klu.open,
    }

In [7]:
code = "eurusd"
begin_time = "2020-01-01"
end_time = None
data_src = DATA_SRC.CSV
lv_list = [KL_TYPE.K_DAY]

config = CChanConfig({
    "trigger_step": True,  # 打开开关！
    "bi_strict": True,
    "skip_step": 0,
    "divergence_rate": float("inf"),
    "bsp2_follow_1": False,
    "bsp3_follow_1": False,
    "min_zs_cnt": 0,
    "bs1_peak": False,
    "macd_algo": "peak",
    "bs_type": '1,2,3a,1p,2s,3b',
    "print_warning": True,
    "zs_algo": "normal",
})

chan = CChan(
    code=code,
    begin_time=begin_time,
    end_time=end_time,
    data_src=data_src,
    lv_list=lv_list,
    config=config,
    autype=AUTYPE.QFQ,
)

bsp_dict: Dict[int, T_SAMPLE_INFO] = {}  # 存储策略产出的bsp的特征

In [8]:
# 跑策略，保存买卖点的特征
for chan_snapshot in chan.step_load():
    last_klu = chan_snapshot[0][-1][-1]
    bsp_list = chan_snapshot.get_bsp()
    if not bsp_list:
        continue
    last_bsp = bsp_list[-1]

    cur_lv_chan = chan_snapshot[0]
    if last_bsp.klu.idx not in bsp_dict and cur_lv_chan[-2].idx == last_bsp.klu.klc.idx:
        # 假如策略是：买卖点分形第三元素出现时交易
        bsp_dict[last_bsp.klu.idx] = {
            "feature": last_bsp.features,
            "is_buy": last_bsp.is_buy,
            "open_time": last_klu.time,
        }
        bsp_dict[last_bsp.klu.idx]['feature'].add_feat(stragety_feature(last_klu))  # 开仓K线特征
        print(last_bsp.klu.time, last_bsp.is_buy)

2020/01/01 19:50 False
2020/01/01 20:05 False
2020/01/01 20:14 False
2020/01/01 20:20 False
2020/01/01 21:33 False
2020/01/01 21:53 False
2020/01/01 23:20 False
2020/01/01 23:32 True
2020/01/01 23:44 True
2020/01/01 23:58 True
2020/01/02 01:27 True
2020/01/02 01:31 True
2020/01/02 01:49 False
2020/01/02 01:52 False
2020/01/02 01:56 True
2020/01/02 02:05 False
2020/01/02 02:14 True
2020/01/02 02:18 True
2020/01/02 02:21 True
2020/01/02 02:31 True
2020/01/02 02:51 False
2020/01/02 02:53 False
2020/01/02 03:02 False
2020/01/02 03:04 False
2020/01/02 03:09 True
2020/01/02 03:15 False
2020/01/02 03:21 False
2020/01/02 03:32 True
2020/01/02 03:39 True
2020/01/02 03:47 False
2020/01/02 03:53 False
2020/01/02 04:00 False
2020/01/02 04:03 False
2020/01/02 04:09 True
2020/01/02 04:37 True
2020/01/02 04:51 True
2020/01/02 04:57 True
2020/01/02 05:09 True
2020/01/02 05:21 True
2020/01/02 05:30 True
2020/01/02 05:43 False
2020/01/02 05:59 False
2020/01/02 06:06 False
2020/01/02 06:09 False
2020/01/02 06:13 True
2020/01/02 06:17 True
2020/01/02 06:33 True
2020/01/02 06:57 True
2020/01/02 07:01 True
2020/01/02 07:49 True
2020/01/02 08:24 False
2020/01/02 08:30 True
2020/01/02 08:35 True
2020/01/02 08:43 True
2020/01/02 08:59 False
2020/01/02 09:10 True
2020/01/02 09:14 True
2020/01/02 09:18 True
2020/01/02 09:37 False
2020/01/02 09:43 True
2020/01/02 09:49 True
2020/01/02 09:52 True
2020/01/02 10:01 False
2020/01/02 10:13 False
2020/01/02 10:17 False
2020/01/02 10:26 True
2020/01/02 10:40 False
2020/01/02 10:46 False
2020/01/02 11:01 False
2020/01/02 12:25 False
2020/01/02 12:32 False
2020/01/02 12:36 False
2020/01/02 13:03 False
2020/01/02 13:17 True
2020/01/02 13:26 False
2020/01/02 13:34 False
2020/01/02 13:37 False
2020/01/02 13:43 False
2020/01/02 13:50 True
2020/01/02 14:00 False
2020/01/02 14:15 False
2020/01/02 14:37 True
2020/01/02 14:42 True
2020/01/02 14:53 False
2020/01/02 15:06 False
2020/01/02 15:15 False
2020/01/02 15:17 False
2020/01/02 15:23 False
2020/01/02 15:27 False
2020/01/02 15:36 True
2020/01/02 15:45 True
2020/01/02 15:49 True
2020/01/02 15:58 True
2020/01/02 16:06 False
2020/01/02 16:09 False
2020/01/02 16:27 False
2020/01/02 16:34 True
2020/01/02 16:45 True
2020/01/02 16:48 True
2020/01/02 16:51 True
2020/01/02 16:55 True
2020/01/02 17:15 True
2020/01/02 18:08 False
2020/01/02 18:14 True
2020/01/02 18:23 False
2020/01/02 18:25 False
2020/01/02 18:30 False
2020/01/02 19:14 False
2020/01/02 19:57 False
2020/01/02 20:15 False
2020/01/02 20:19 False
2020/01/02 20:56 False
2020/01/02 21:17 False
2020/01/02 21:30 False
2020/01/02 22:00 True
2020/01/02 22:05 True
2020/01/02 22:18 True
2020/01/02 22:23 True
2020/01/02 22:46 False
2020/01/02 22:57 False
2020/01/02 23:07 False
2020/01/02 23:21 True
2020/01/02 23:25 True
2020/01/02 23:29 True
2020/01/02 23:43 True
2020/01/02 23:48 True
2020/01/02 23:57 True
2020/01/03 00:20 True
2020/01/03 00:27 True
2020/01/03 00:35 False
2020/01/03 00:42 False
2020/01/03 00:53 False
2020/01/03 01:01 True
2020/01/03 01:03 True
2020/01/03 01:59 True
2020/01/03 02:04 True
2020/01/03 02:20 True
2020/01/03 02:40 True
2020/01/03 02:53 True
2020/01/03 03:00 True
2020/01/03 03:17 True
2020/01/03 03:23 True
2020/01/03 03:26 True
2020/01/03 03:47 True
2020/01/03 03:51 True
2020/01/03 03:58 True
2020/01/03 04:02 True
2020/01/03 04:12 True
2020/01/03 04:17 True
2020/01/03 04:20 True
2020/01/03 04:46 True
2020/01/03 04:55 True
2020/01/03 05:00 True
2020/01/03 05:13 True
2020/01/03 05:27 True
2020/01/03 05:39 True
2020/01/03 06:06 True
2020/01/03 06:11 True
2020/01/03 06:35 True
2020/01/03 06:48 True
2020/01/03 07:52 True
2020/01/03 08:03 False
2020/01/03 08:13 False
2020/01/03 08:22 False
2020/01/03 08:40 False
2020/01/03 08:47 True
2020/01/03 08:51 True
2020/01/03 08:55 True
2020/01/03 09:02 True
2020/01/03 09:53 True
2020/01/03 09:58 True
2020/01/03 10:55 False
2020/01/03 11:20 False
2020/01/03 11:38 False
2020/01/03 11:55 False
2020/01/03 11:59 True
2020/01/03 12:13 True
2020/01/03 12:21 False
2020/01/03 12:38 True
2020/01/03 12:41 True
2020/01/03 12:52 False
2020/01/03 13:05 True
2020/01/03 13:25 True
2020/01/03 13:34 True
2020/01/03 13:40 True
2020/01/03 14:02 True
2020/01/03 14:12 True
2020/01/03 14:22 True
2020/01/03 14:59 False
2020/01/03 15:06 True
2020/01/03 15:13 True
2020/01/03 15:23 True
2020/01/03 15:38 True
2020/01/03 15:55 True
2020/01/03 15:57 True
2020/01/03 16:14 True
2020/01/03 16:19 True
2020/01/03 16:46 True
2020/01/03 16:49 True
2020/01/03 16:52 True
2020/01/05 18:23 True
2020/01/05 18:38 True
2020/01/05 18:52 True
2020/01/05 19:00 True
2020/01/05 19:26 False
2020/01/05 19:33 True
2020/01/05 19:39 True
2020/01/05 19:57 True
2020/01/05 20:13 True
2020/01/05 20:26 False
2020/01/05 20:31 False
2020/01/05 20:37 True
2020/01/05 20:47 False
2020/01/05 20:50 False
2020/01/05 21:02 False
2020/01/05 21:22 True
2020/01/05 21:35 False
2020/01/05 21:47 False
2020/01/05 21:52 False
2020/01/05 22:05 False
2020/01/05 22:12 False
2020/01/05 22:26 False
2020/01/05 22:34 False
2020/01/06 False
2020/01/06 00:50 True
2020/01/06 01:17 True
2020/01/06 01:19 True
2020/01/06 01:41 True
2020/01/06 01:53 False
2020/01/06 02:01 False
2020/01/06 02:05 False
2020/01/06 02:19 True
2020/01/06 02:46 False
2020/01/06 02:48 False
2020/01/06 02:51 False
2020/01/06 02:55 False
2020/01/06 03:02 False
2020/01/06 03:11 True
2020/01/06 03:15 True
2020/01/06 03:25 False
2020/01/06 03:38 False
2020/01/06 03:40 False
2020/01/06 03:44 False
2020/01/06 03:50 False
2020/01/06 04:03 False
2020/01/06 04:32 False
2020/01/06 04:47 False
2020/01/06 05:01 False
2020/01/06 05:13 False
2020/01/06 05:17 False
2020/01/06 05:24 False
2020/01/06 05:42 False
2020/01/06 06:06 False
2020/01/06 06:16 False
2020/01/06 06:32 False
2020/01/06 06:51 False
2020/01/06 07:05 True
2020/01/06 07:09 True
2020/01/06 07:14 True
2020/01/06 07:19 True
2020/01/06 07:40 True
2020/01/06 08:12 True
2020/01/06 08:17 True
2020/01/06 08:48 True
2020/01/06 09:07 True
2020/01/06 09:16 True
2020/01/06 09:27 True
2020/01/06 09:42 True
2020/01/06 09:46 True
2020/01/06 09:53 True
2020/01/06 09:59 True
2020/01/06 10:07 False
2020/01/06 10:20 True
2020/01/06 10:25 True
2020/01/06 10:34 False
2020/01/06 10:40 True
2020/01/06 10:45 True
2020/01/06 11:15 True
2020/01/06 11:52 True
2020/01/06 12:02 True
2020/01/06 12:13 False
2020/01/06 12:17 False
2020/01/06 13:01 False
2020/01/06 13:41 False
2020/01/06 13:45 False
2020/01/06 14:09 False
2020/01/06 14:21 True
2020/01/06 14:40 True
2020/01/06 14:44 True
2020/01/06 14:59 False
2020/01/06 15:11 True
2020/01/06 15:32 True
2020/01/06 15:38 True
2020/01/06 15:48 True
2020/01/06 15:53 False
2020/01/06 15:59 False
2020/01/06 16:12 False
2020/01/06 16:16 True
2020/01/06 16:26 False
2020/01/06 16:45 False
2020/01/06 18:03 False
2020/01/06 18:52 False
2020/01/06 19:04 True
2020/01/06 19:15 False
2020/01/06 19:31 True
2020/01/06 19:42 True
2020/01/06 19:52 True
2020/01/06 19:59 True
2020/01/06 20:12 False
2020/01/06 20:23 False
2020/01/06 20:29 False
2020/01/06 20:44 False
2020/01/06 20:54 True
2020/01/06 21:01 True
2020/01/06 21:08 True
2020/01/06 21:29 True
2020/01/06 21:44 True
2020/01/06 22:14 False
2020/01/06 22:20 False
2020/01/06 22:36 False
2020/01/06 22:46 True
2020/01/06 22:49 True
2020/01/06 23:00 True
2020/01/06 23:08 True
2020/01/06 23:16 False
2020/01/06 23:26 False
2020/01/06 23:32 True
2020/01/06 23:40 True
2020/01/06 23:51 False
2020/01/07 00:01 True
2020/01/07 00:07 False
2020/01/07 00:24 True
2020/01/07 00:46 True
2020/01/07 01:01 True
2020/01/07 01:22 True
2020/01/07 01:40 False
2020/01/07 02:01 True
2020/01/07 02:19 True
2020/01/07 02:32 True
2020/01/07 03:00 True
2020/01/07 03:16 True
2020/01/07 03:22 False
2020/01/07 03:25 False
2020/01/07 03:30 False
2020/01/07 03:35 False
2020/01/07 03:40 False
2020/01/07 03:50 False
2020/01/07 03:56 True
2020/01/07 04:04 False
2020/01/07 04:35 False
2020/01/07 04:41 False
2020/01/07 04:48 True
2020/01/07 04:55 False
2020/01/07 05:00 False
2020/01/07 05:19 True
2020/01/07 05:25 True
2020/01/07 05:48 False
2020/01/07 05:56 False
2020/01/07 06:01 False
2020/01/07 06:07 True
2020/01/07 06:12 True
2020/01/07 06:21 False
2020/01/07 06:27 False
2020/01/07 06:29 False
2020/01/07 06:36 False
2020/01/07 06:42 False
2020/01/07 06:47 False
2020/01/07 07:03 False
2020/01/07 07:13 False
2020/01/07 07:22 True
2020/01/07 07:56 True
2020/01/07 08:02 False
2020/01/07 08:11 True
2020/01/07 08:16 True
2020/01/07 08:23 False
2020/01/07 08:33 True
2020/01/07 08:59 True
2020/01/07 09:26 True
2020/01/07 09:32 True
2020/01/07 09:37 True
2020/01/07 09:53 True
2020/01/07 10:00 True
2020/01/07 10:19 True
2020/01/07 10:23 True
2020/01/07 10:45 True
2020/01/07 11:14 True
2020/01/07 11:23 True
2020/01/07 11:43 True
2020/01/07 12:02 False
2020/01/07 12:19 False
2020/01/07 12:41 False
2020/01/07 13:07 False
2020/01/07 13:12 False
2020/01/07 13:18 False
2020/01/07 13:24 False
2020/01/07 13:26 False
2020/01/07 13:35 True
2020/01/07 13:55 False
2020/01/07 14:02 True
2020/01/07 14:32 False
2020/01/07 14:36 True
2020/01/07 14:40 True
2020/01/07 15:03 False
2020/01/07 15:08 False
2020/01/07 15:38 True
2020/01/07 15:45 True
2020/01/07 15:49 True
2020/01/07 16:14 False
2020/01/07 16:20 False
2020/01/07 16:31 False
2020/01/07 16:41 False
2020/01/07 17:00 False
2020/01/07 17:08 True
2020/01/07 17:13 True
2020/01/07 17:36 True
2020/01/07 17:40 True
2020/01/07 17:50 False
2020/01/07 17:52 False
2020/01/07 18:02 False
2020/01/07 18:27 False
2020/01/07 18:59 False
2020/01/07 19:03 False
2020/01/07 19:06 False
2020/01/07 19:08 False
2020/01/07 19:12 False
2020/01/07 19:14 False
2020/01/07 21:20 False
2020/01/07 21:35 True
2020/01/07 21:43 True
2020/01/07 21:53 False
2020/01/07 22:00 True
2020/01/07 22:03 True
2020/01/07 22:07 True
2020/01/07 22:12 True
2020/01/07 22:16 True
2020/01/07 22:28 True
2020/01/07 22:44 True
2020/01/07 22:52 True
2020/01/07 23:07 False
2020/01/07 23:11 False
2020/01/07 23:14 False
2020/01/07 23:33 True
2020/01/07 23:39 True
2020/01/07 23:53 True
2020/01/08 00:32 False
2020/01/08 00:39 False
2020/01/08 00:48 True
2020/01/08 00:54 True
2020/01/08 00:56 True
2020/01/08 00:58 True
2020/01/08 01:26 False
2020/01/08 01:40 True
2020/01/08 01:58 True
2020/01/08 02:03 True
2020/01/08 02:12 True
2020/01/08 02:19 True
2020/01/08 02:29 True
2020/01/08 02:35 True
2020/01/08 02:59 True
2020/01/08 03:04 True
2020/01/08 03:13 True
2020/01/08 03:18 True
2020/01/08 03:37 True
2020/01/08 03:58 True
2020/01/08 04:04 True
2020/01/08 04:14 True
2020/01/08 04:51 True
2020/01/08 05:01 True
2020/01/08 05:12 True
2020/01/08 05:14 True
2020/01/08 05:18 True
2020/01/08 05:26 True
2020/01/08 05:33 True
2020/01/08 05:37 True
2020/01/08 05:56 True
2020/01/08 06:21 True
2020/01/08 06:38 True
2020/01/08 06:47 False
2020/01/08 06:56 True
2020/01/08 07:02 False
2020/01/08 07:10 True
2020/01/08 07:15 False
2020/01/08 07:28 True
2020/01/08 07:45 True
2020/01/08 07:53 True
2020/01/08 07:57 True
2020/01/08 08:01 True
2020/01/08 08:06 False
2020/01/08 08:08 False
2020/01/08 08:13 True
2020/01/08 08:15 True
2020/01/08 08:45 True
2020/01/08 08:54 False
2020/01/08 08:57 False
2020/01/08 09:01 False
2020/01/08 09:19 False
2020/01/08 09:21 False
2020/01/08 09:31 False
2020/01/08 09:38 True
2020/01/08 09:45 True
2020/01/08 09:53 False
2020/01/08 09:59 False
2020/01/08 10:01 False
2020/01/08 10:07 False
2020/01/08 10:17 True
2020/01/08 10:34 True
2020/01/08 10:44 False
2020/01/08 10:49 True
2020/01/08 10:52 True
2020/01/08 10:57 True
2020/01/08 11:05 True
2020/01/08 11:11 True
2020/01/08 11:29 True
2020/01/08 11:44 False
2020/01/08 11:47 False
2020/01/08 12:02 False
2020/01/08 12:12 False
2020/01/08 12:23 True
2020/01/08 12:29 True
2020/01/08 12:36 True
2020/01/08 12:41 True
2020/01/08 12:45 True
2020/01/08 12:55 False
2020/01/08 12:59 False
2020/01/08 13:11 True
2020/01/08 13:51 True
2020/01/08 13:53 True
2020/01/08 14:16 True
2020/01/08 14:19 True
2020/01/08 14:22 True
2020/01/08 14:44 True
2020/01/08 14:49 True
2020/01/08 14:58 False
2020/01/08 15:08 True
2020/01/08 15:12 False
2020/01/08 15:25 False
2020/01/08 15:35 False
2020/01/08 15:50 False
2020/01/08 15:54 False
2020/01/08 16:05 True
2020/01/08 16:11 True
2020/01/08 16:23 False
2020/01/08 16:47 True
2020/01/08 16:57 True
2020/01/08 17:26 False
2020/01/08 18:02 True
2020/01/08 18:30 False
2020/01/08 18:40 False
2020/01/08 19:00 False
2020/01/08 19:08 False
2020/01/08 19:20 True
2020/01/08 19:33 False
2020/01/08 19:38 False
2020/01/08 19:47 True
2020/01/08 20:10 False
2020/01/08 20:19 True
2020/01/08 20:29 False
2020/01/08 21:02 True
2020/01/08 21:23 True
2020/01/08 21:47 True
2020/01/08 21:53 True
2020/01/08 22:01 True
2020/01/08 22:51 True
2020/01/08 23:02 True
2020/01/08 23:08 True
2020/01/08 23:12 True
2020/01/08 23:18 True
2020/01/08 23:31 False
2020/01/08 23:38 False
2020/01/08 23:45 False
2020/01/09 00:07 False
2020/01/09 00:22 False
2020/01/09 00:25 False
2020/01/09 00:28 False
2020/01/09 00:39 False
2020/01/09 00:55 False
2020/01/09 01:01 False
2020/01/09 01:06 False
2020/01/09 01:51 False
2020/01/09 01:57 True
2020/01/09 02:01 True
2020/01/09 02:09 False
2020/01/09 02:15 True
2020/01/09 02:29 False
2020/01/09 02:33 False
2020/01/09 02:38 False
2020/01/09 02:43 False
2020/01/09 02:47 False
2020/01/09 02:52 True
2020/01/09 02:57 True
2020/01/09 03:02 True
2020/01/09 03:25 False
2020/01/09 03:37 False
2020/01/09 03:44 False
2020/01/09 03:50 False
2020/01/09 04:02 False
2020/01/09 04:09 False
2020/01/09 04:46 True
2020/01/09 04:52 True
2020/01/09 04:59 True
2020/01/09 05:03 True
2020/01/09 05:10 True
2020/01/09 05:35 False
2020/01/09 05:44 False
2020/01/09 05:51 True
2020/01/09 05:56 True
2020/01/09 06:09 False
2020/01/09 06:13 False
2020/01/09 06:18 True
2020/01/09 06:25 True
2020/01/09 06:29 True
2020/01/09 06:46 True
2020/01/09 06:53 False
2020/01/09 07:02 True
2020/01/09 07:08 False
2020/01/09 07:23 True
2020/01/09 07:27 True
2020/01/09 07:35 False
2020/01/09 07:44 True
2020/01/09 07:47 True
2020/01/09 07:56 False
2020/01/09 08:03 True
2020/01/09 08:10 True
2020/01/09 08:16 True
2020/01/09 08:22 True
2020/01/09 08:28 False
2020/01/09 08:31 False
2020/01/09 08:39 False
2020/01/09 08:45 False
2020/01/09 09:02 True
2020/01/09 09:05 True
2020/01/09 09:10 True
2020/01/09 09:20 True
2020/01/09 09:23 True
2020/01/09 09:38 False
2020/01/09 09:43 False
2020/01/09 09:46 False
2020/01/09 09:59 False
2020/01/09 10:20 True
2020/01/09 10:26 False
2020/01/09 10:40 True
2020/01/09 11:08 True
2020/01/09 11:11 True
2020/01/09 11:21 True
2020/01/09 11:46 False
2020/01/09 11:52 False
2020/01/09 12:00 False
2020/01/09 12:05 False
2020/01/09 12:16 False
2020/01/09 12:30 False
2020/01/09 13:22 False
2020/01/09 13:27 False
2020/01/09 13:42 False
2020/01/09 14:08 False
2020/01/09 14:20 False
2020/01/09 14:24 False
2020/01/09 14:47 False
2020/01/09 15:11 False
2020/01/09 15:32 True
2020/01/09 15:43 True
2020/01/09 15:49 True
2020/01/09 16:00 False
2020/01/09 16:23 True
2020/01/09 16:26 True
2020/01/09 16:29 True
2020/01/09 16:45 False
2020/01/09 16:50 False
2020/01/09 17:00 True
2020/01/09 17:09 True
2020/01/09 17:21 False
2020/01/09 17:35 True
2020/01/09 17:43 True
2020/01/09 17:50 False
2020/01/09 18:05 False
2020/01/09 18:21 False
2020/01/09 18:35 True
2020/01/09 18:51 False
2020/01/09 19:00 False
2020/01/09 19:12 True
2020/01/09 19:16 True
2020/01/09 19:35 False
2020/01/09 19:44 True
2020/01/09 19:47 True
2020/01/09 20:02 True
2020/01/09 20:17 True
2020/01/09 20:24 True
2020/01/09 20:32 False
2020/01/09 20:37 False
2020/01/09 20:50 True
2020/01/09 21:10 False
2020/01/09 21:14 False
2020/01/09 21:22 True
2020/01/09 21:34 True
2020/01/09 21:48 False
2020/01/09 21:57 False
2020/01/09 21:59 False
2020/01/09 22:24 False
2020/01/09 23:15 False
2020/01/09 23:25 False
2020/01/09 23:34 False
2020/01/10 00:06 False
2020/01/10 00:13 False
2020/01/10 00:18 False
2020/01/10 00:32 False
2020/01/10 00:44 False
2020/01/10 00:49 False
2020/01/10 01:35 True
2020/01/10 02:02 False
2020/01/10 02:33 True
2020/01/10 02:42 True
2020/01/10 02:48 True
2020/01/10 02:57 True
2020/01/10 03:21 True
2020/01/10 03:24 True
2020/01/10 03:33 True
2020/01/10 03:36 True
2020/01/10 03:44 True
2020/01/10 03:59 False
2020/01/10 04:16 True
2020/01/10 04:28 True
2020/01/10 04:49 False
2020/01/10 04:55 True
2020/01/10 05:10 False
2020/01/10 05:20 True
2020/01/10 05:36 True
2020/01/10 05:41 True
2020/01/10 05:51 True
2020/01/10 06:03 True
2020/01/10 06:48 True
2020/01/10 07:01 True
2020/01/10 07:31 False
2020/01/10 07:46 False
2020/01/10 07:50 False
2020/01/10 07:59 False
2020/01/10 08:03 False
2020/01/10 08:13 True
2020/01/10 08:17 True
2020/01/10 08:23 False
2020/01/10 08:27 False
2020/01/10 08:31 False
2020/01/10 09:05 True
2020/01/10 09:10 False
2020/01/10 09:18 True
2020/01/10 09:28 False
2020/01/10 09:39 False
2020/01/10 09:49 True
2020/01/10 09:59 False
2020/01/10 10:13 False
2020/01/10 10:19 False
2020/01/10 10:22 False
2020/01/10 10:50 False
2020/01/10 11:22 False
2020/01/10 11:24 False
2020/01/10 11:29 True
2020/01/10 11:37 False
2020/01/10 11:52 False
2020/01/10 12:00 False
2020/01/10 12:05 False
2020/01/10 12:18 False
2020/01/10 12:21 False
2020/01/10 12:25 False
2020/01/10 13:27 False
2020/01/10 13:31 False
2020/01/10 13:50 False
2020/01/10 14:04 True
2020/01/10 14:11 False
2020/01/10 14:17 True
2020/01/10 14:26 False
2020/01/10 14:34 False
2020/01/10 14:42 False
2020/01/10 14:49 False
2020/01/10 14:58 False
2020/01/10 15:04 True
2020/01/10 15:07 True
2020/01/10 15:17 False
2020/01/10 15:30 True
2020/01/10 15:35 True
2020/01/10 15:55 True
2020/01/10 16:06 False
2020/01/10 16:30 True
2020/01/10 16:48 False
2020/01/12 17:00 True
2020/01/12 17:36 True
2020/01/12 18:14 False
2020/01/12 18:24 True
2020/01/12 18:26 True
2020/01/12 18:38 True
2020/01/12 18:59 True
2020/01/12 19:07 False
2020/01/12 19:15 False
2020/01/12 19:32 True
2020/01/12 19:43 False
2020/01/12 19:48 False
2020/01/12 19:52 False
2020/01/12 20:01 False
2020/01/12 20:06 True
2020/01/12 20:15 False
2020/01/12 20:26 False
2020/01/12 20:31 False
2020/01/12 20:51 False
2020/01/12 20:58 False
2020/01/12 21:30 False
2020/01/12 22:11 False
2020/01/12 22:42 False
2020/01/12 22:52 False
2020/01/12 23:11 False
2020/01/12 23:25 False
2020/01/13 00:10 False
2020/01/13 00:48 False
2020/01/13 01:22 False
2020/01/13 01:29 False
2020/01/13 01:48 False
2020/01/13 02:25 True
2020/01/13 02:31 False
2020/01/13 02:36 False
2020/01/13 02:41 False
2020/01/13 02:46 False
2020/01/13 02:58 True
2020/01/13 03:07 False
2020/01/13 03:12 True
2020/01/13 03:21 True
2020/01/13 03:28 True
2020/01/13 03:33 False
2020/01/13 03:43 False
2020/01/13 03:49 True
2020/01/13 03:59 False
2020/01/13 04:03 False
2020/01/13 04:07 True
2020/01/13 04:18 True
2020/01/13 04:42 False
2020/01/13 05:00 True
2020/01/13 05:11 False
2020/01/13 05:20 False
2020/01/13 05:32 True
2020/01/13 05:38 False
2020/01/13 05:52 True
2020/01/13 06:07 False
2020/01/13 06:10 False
2020/01/13 06:18 True
2020/01/13 06:27 False
2020/01/13 06:44 True
2020/01/13 06:47 True
2020/01/13 07:04 True
2020/01/13 07:25 False
2020/01/13 07:29 False
2020/01/13 07:33 False
2020/01/13 07:44 True
2020/01/13 07:48 True
2020/01/13 07:59 False
2020/01/13 08:05 False
2020/01/13 08:09 False
2020/01/13 08:13 True
2020/01/13 08:21 True
2020/01/13 08:25 True
2020/01/13 08:32 True
2020/01/13 08:40 True
2020/01/13 08:54 True
2020/01/13 08:59 True
2020/01/13 09:03 True
2020/01/13 09:16 False
2020/01/13 09:26 True
2020/01/13 09:35 False
2020/01/13 09:40 True
2020/01/13 09:45 True
2020/01/13 09:51 True
2020/01/13 09:58 True
2020/01/13 10:08 False
2020/01/13 10:16 True
2020/01/13 10:24 False
2020/01/13 10:33 False
2020/01/13 10:44 False
2020/01/13 10:57 True
2020/01/13 11:00 True
2020/01/13 11:15 False
2020/01/13 11:31 False
2020/01/13 11:50 False
2020/01/13 12:00 True
2020/01/13 12:06 False
2020/01/13 12:14 False
2020/01/13 12:22 False
2020/01/13 12:33 True
2020/01/13 12:37 True
2020/01/13 12:49 False
2020/01/13 12:57 False
2020/01/13 13:02 False
2020/01/13 13:07 True
2020/01/13 13:19 False
2020/01/13 13:24 True
2020/01/13 13:39 True

CChanException: kline time err, cur=2020/10/25 19:00, last=2020/10/25 19:00

In [ ]:
# 生成libsvm样本特征
bsp_academy = [bsp.klu.idx for bsp in chan.get_bsp()]
feature_meta = {}  # 特征meta
cur_feature_idx = 0
plot_marker = {}
fid = open("feature.libsvm", "w")
for bsp_klu_idx, feature_info in bsp_dict.items():
    label = int(bsp_klu_idx in bsp_academy)  # 以买卖点识别是否准确为label
    features = []  # List[(idx, value)]
    for feature_name, value in feature_info['feature'].items():
        if feature_name not in feature_meta:
            feature_meta[feature_name] = cur_feature_idx
            cur_feature_idx += 1
        features.append((feature_meta[feature_name], value))
    features.sort(key=lambda x: x[0])
    feature_str = " ".join([f"{idx}:{value}" for idx, value in features])
    fid.write(f"{label} {feature_str}\n")
    plot_marker[feature_info["open_time"].to_str()] = ("√" if label else "×", "down" if feature_info["is_buy"] else "up")
fid.close()

In [ ]:
with open("feature.meta", "w") as fid:
    # meta保存下来，实盘预测时特征对齐用
    fid.write(json.dumps(feature_meta))

In [ ]:
# 画图检查label是否正确
plot(chan, plot_marker)

In [ ]:
# load sample file & train model
dtrain = xgb.DMatrix("feature.libsvm?format=libsvm")  # load sample
param = {'max_depth': 2, 'eta': 0.3, 'objective': 'binary:logistic', 'eval_metric': 'auc'}
evals_result = {}
bst = xgb.train(
    param,
    dtrain=dtrain,
    num_boost_round=10,
    evals=[(dtrain, "train")],
    evals_result=evals_result,
    verbose_eval=True,
)
bst.save_model("model.json")

In [ ]:
# load model
model = xgb.Booster()
model.load_model("model.json")

In [ ]:
# predict
print(model.predict(dtrain))